ARG REGISTRY_NAME
# FROM ${REGISTRY_NAME}/baseimages/node:9-alpine
FROM ${REGISTRY_NAME}/baseimages/node:12.19-alpine3.9

COPY . /src
RUN cd /src && npm install
EXPOSE 80
CMD ["node", "/src/server.js"]
